### ISSUE TITLE
(Huge) Database Modification

### ISSUE THREAD

**Issue by KamiliArsyad** [florentianayuwono/DigitalIT#41]
Details in comment.

**Comment by KamiliArsyad** [comment]
In order to accommodate our business recommendation feature, the current database is not sufficient. New tables must be created, relations re-mapped, and other modifications.

## Target
Below is the new database schema design:
![image](https://user-images.githubusercontent.com/22293969/178189362-9fae2b3b-2b51-4a72-bd57-eb33891295d5.png)

Steps needed to do this modification are visualized in the picture below:
![image](https://user-images.githubusercontent.com/22293969/178189516-54ef8eb4-1a6c-412c-927c-585cf260ed43.png)

## Tasks
- [ ] Create experimental database 💾 
- [ ] Create a new branch and link the branch to the experimental database 🔌 
- [ ] Modify `database.sql` and use it as an input for the experimental database 🔧 
- [ ] Modify the controllers of the new branch so that the current features are working well with the new database design 🔧 
- [ ] Check stuff up, merge, and modify the main database✅

**Comment by florentianayuwono** [comment]
STORE and PLATFORM is kind of the same right? Why need to make double?

PRODUCT_MAIN
For product_importance, I think this thing we can make our own judgement. Because if we let the user to key in importance they might not know very well. My approach is that if they key in the product_pirce < 500K NOT URGENT (Shopee), 500K - 1M URGENT (Tokopedia or Bukalapak), > 1M VERY URGENT (Tokopedia).

For population target, I think what we want is more of SHOPPER_AGE target. My approach is < 35 yo (Shopee and Tokopedia), > 35 yo (Tokopedia and Bukalapak)

PRODUCT_SALES
Not sure what date_range functionality is? If we already have input_date, then I think we can comfortably filter the data for daily, monthly, or ever yearly?
Not sure what local_profit is referring to?

PRODUCT_SECONDARY
Not sure diff with the PRODUCT_SALES.

**Comment by KamiliArsyad** [comment]
### Store and Platform
Differentiation between store and platform is for scalability. Instead of writing "Shopee" as separate data for each business that has a store on Shopee, all of them refer to the same platform ID instead. This way if later on we want to scale the platform, make custom API for the platform, and automate the platform profile specification that we use for recommendation, we can scale it easily.

### Product_main
Product importance is a private field (as I specified on OneNote) and the one who'll be assigning the category won't be the client but someone with an admin role later on (if there is one). Also the category is not importance from 1 to 10 kind of thing but more of a primary, secondary, and tertiary need kind of importance.

As for the population target, yup, it's actually shopper age target (I couldn't find the right word). The integer value I put inside is for categorization and not for age value. The plan is to divide the whole populations to age ranges such as children, teen, adult, elder, all ages, etc. and assign each population a number for categorization.

## product_sales
date_range is again a numerical categorization. The idea comes from trying to simplify the proper way of doing it which is to create a `product_sales` table for each date range (e.g. `product_sales_daily`, `product_sales_weekly`, and `produt_sales_monthly) but that would be too complex to implement in our current setup and will also be kind of an overkill scalability. I decided that it'd be better to just keep everyting in one table for now, specifying which `date_range` the user is inputting by adding a `date_range` column.

Local profit refers to how much profit a particular business has created in each time they input a data. The plan is to create a global sales table for querying and calculating the data needed to create a global summary of each product (case where the same product is being sold by different businesses).

## product_secondary
This is the product table for each business. The idea can be seen inside note in OneNote since that's my thought process. So basically there's the product table that keeps track of what kinds of products are there, and there's a product table that keeps track of what products are being sold by each business.
This design provides better scalability and relational mapping since the same product that is being sold by multiple businesses is now 'connected' in a way even though they have different prices, costs, stores, etc. and thus provides us with the capability of querying and calculating a summary of a product globally across all businesses.
